### ISSUE TITLE
Blank options screen

### ISSUE THREAD

**Issue by lathidadia** [sylouuu/chrome-tab-modifier#19]
![image](https://cloud.githubusercontent.com/assets/17485874/13339982/cfeb1df6-dc80-11e5-9c00-958b5be888dc.png)

**Comment by lathidadia** [comment]
Tried re-downloading it multiple times, didn't make a difference.

**Comment by sylouuu** [comment]
Hi @lathidadia,

Just check on my computer and it's OK.

Could you do theses steps:

1. Right click on the options page: Inspect
2. Go to Console tab
3. Refresh
4. Capture your screen

Bests

**Comment by lathidadia** [comment]
Hello Syl,

  20160229_083648.jpg
<https://drive.google.com/file/d/0B6uCFaQrOLmDMkFHV29vS1R5ZWM/view?usp=drivesdk>

Hi @lathidadia <https://github.com/lathidadia>,

Just check on my computer and it's OK.

Could you do theses steps:

   1. Right click on the options page: Inspect
   2. Go to Console tab
   3. Refresh
   4. Capture your screen

Bests

—
Reply to this email directly or view it on GitHub
<https://github.com/sylouuu/chrome-tab-modifier/issues/19#issuecomment-189161365>
.

**Comment by sylouuu** [comment]
Hi @lathidadia,

I don't have any access to view your file, please answer from GitHub, not by your inbox and please drag your file here.

Bests

**Comment by lathidadia** [comment]
![image](https://cloud.githubusercontent.com/assets/17485874/13476019/e0ea0908-e119-11e5-9649-a50b2017d592.png)

**Comment by lathidadia** [comment]
![image](https://cloud.githubusercontent.com/assets/17485874/13480715/ecfcce0a-e133-11e5-8617-21ea04c2b8aa.png)

**Comment by lathidadia** [comment]
![image](https://cloud.githubusercontent.com/assets/17485874/13480745/15762e1c-e134-11e5-9b93-3f2580cbad53.png)

**Comment by sylouuu** [comment]
I never seen something like that, no apparently error.

- What Chrome version are you using?
- Check that you have the latest Tab Modifier version, 0.9.3: [chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai](chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai)
- Are you in a company private network with restrictions or home network without firewall?
- Make another screenshot with the "Network > All" tab

Bests

**Comment by bezirg** [comment]
Also affected here on Linux, Chrome Version 47.0.2526.73 (64-bit)

**Comment by sylouuu** [comment]
Hi @bezirg,

I just installed a fresh Ubuntu 14.04 version with the latest Chrome (49) and it's OK.

- Can you update your Chrome?
- Can you tell me what Linux distribution are you using?

Bests

**Comment by lathidadia** [comment]
Our firewall was blocking it (at work) and it works ok when I installed it
again at home.

**Comment by sylouuu** [comment]
Glad it's OK for you @lathidadia.

Bests

**Comment by bezirg** [comment]
I still have it w/o firewall, i will try to update my chrome

**Comment by hlein** [comment]
[Since this issue has already been closed, perhaps I should open a new one instead...]

I am having this exact same issue.  chromium-49.0.2623.87 on Gentoo Linux, Tab Modifier version 0.9.3.  Same behavior whether I pass traffic through a Squid proxy or go direct.  Tried disabling all other extensions, no change.

Maybe some font issue?  I can see that the "blank" pages are reactive to user input, indeed I can click around to bring up some sub-menus etc., which do show some text and decorations; see the screenshot.

![tab-modifier-blank](https://cloud.githubusercontent.com/assets/4372440/14031345/d441ed72-f1e2-11e5-9ac8-c3f8010d2e6f.png)

**Comment by sylouuu** [comment]
Hi @hlein,

Can you see some messages in the browser console?

Bests

**Comment by hlein** [comment]
Hm, nope there are no messages/errors in the console (you mean from ctrl-shift-j, right?)

I noticed something else.  If I mouse-select over the area that has no visible text, I can paste into an xterm or whatever and get readable text.

So that makes me think the text is there, it's just rendering in an invisibly small font and/or colors that make it invisible.  Thus - no "error" to speak of.

I drilled into the elements in the console, maybe this screenshot will give you some insight into what's going on (it does not really help me ;).

Thanks!

![tab-modifier-elements](https://cloud.githubusercontent.com/assets/4372440/14034000/56c85d32-f1f5-11e5-84b5-f8f36718b9a6.png)

**Comment by sylouuu** [comment]
Hi @hlein,

Thank's for the screenshot. 

- Can you try with Chrome instead of Chromium?
- Can you try to update Chromium to version 51?

I've downloaded and tested with Chromium 51 on Windows, it's OK for me.

Bests

**Comment by hlein** [comment]
Hi,

I tried installing/upgrading both Chrome 51.0.2687.0 and Chromium 51.0.2687.0 on Gentoo Linux, same behavior.

During Chrome installation I saw a warning to make sure I had some particular font packages installed; I also installed them, but same behavior as before.

**Comment by sylouuu** [comment]
Hey,

I suggest that Gentoo can't "read" the web font "**Fira Sans**" used by the extension.

Can you the font on theses pages ?

- https://www.fontsquirrel.com/fonts/fira-sans
- https://www.google.com/fonts/specimen/Fira+Sans

I also found this [article](http://www.makeuseof.com/tag/quickly-install-googles-web-fonts-on-your-linux-computer/).

Otherwise try to [install it](https://packages.gentoo.org/packages/media-fonts/fira-sans).

HTH ;)

**Comment by hlein** [comment]
> I suggest that Gentoo can't "read" the web font "Fira Sans" used by the extension.

Bingo!  I did not have that font installed.  It was available; I installed it (using "emerge media-fonts/fira-sans") and restarted Chrome / Chromium and the extension's options page looks perfect now.  Gentoo packages can specify other packages (including fonts) as dependencies so they get installed automatically, but apparenlty fira-sans is not a dep for either chromium or chrome.

@lathidadia and @bezirg , if you still have Linux systems where you are having this issue, make sure you have fira-sans installed.

@sylouuu I don't know if you want to put some kind of font sanity-check in a future version so you can present an error/warning message in a more generic font telling the user how to fix it :)  Perhaps this issue will be sufficient.

**Comment by sylouuu** [comment]
@hlein Glad we have found the issue and thank you for your patience. :)

I just added a note to the README file about this behavior.

Enjoy Tab Modifier! :+1:

**Comment by sylouuu** [comment]
Fira Sans will not be more a problem, the fond has been removed in 0.12.1.
