### ISSUE TITLE
The following actions will be applied when the URL starts with starts.with.this:

### ISSUE THREAD

**Issue by HatisEm** [sylouuu/chrome-tab-modifier#31]
Can you add a new feature that lets you change a tab that starts with, for example, www.youtube.com?

When I add a rule to change the tab of "www.TabRuleURL.com" and visit any site and add "www.TabRuleURL.com" at the end, for example, "www.facebook.com/www.TabRuleURL.com" the extension thinks that it's the same site and changes the tab based on the rule I made for "www.TabRuleURL.com"

Thanks in advance

**Comment by sylouuu** [comment]
Hi @HatisEm,

This is an expected behavior because `www.facebook.com/www.TabRuleURL.com` contains `www.TabRuleURL.com`.

Sometimes you want this behavior so I can't change it.

If it fits your needs, you can set a more accurate URL matcher like `http://www.TabRuleURL.com`.

Otherwise, there is a feature idea such as: the user may choose the URL matcher type:

- Starts with
- Contains
- Ends with

I keep this feature in mind but I won't change the default behavior "**contains**" for the moment.

Thank you for your report.

Bests

**Comment by sylouuu** [comment]
Finally available in 0.15.0.
