### ISSUE TITLE
Issue when referencing none HTML content

### ISSUE THREAD

**Issue by vaff** [sylouuu/chrome-tab-modifier#60]
I'm currently using and loving the extension. But I have a issue when visiting a page that isn't HTML content. 

Here is an example of viewing a JSON response:
![screen shot 2017-01-26 at 11 50 55](https://cloud.githubusercontent.com/assets/351447/22328725/104b53d0-e3be-11e6-81b5-a797b0eecbe7.png)

I'm using the {title} tag. And it shows as so, without a proper fallback.

**Comment by sylouuu** [comment]
Since Javascript considers each page as HTML, even a `.json` it would be hard to find a way to create a fallback. A little part of users like you will understand why it prints "<DEV> {title}" as it didn't find a title inside the page. I think it's OK.

I checked the [webRequest API](https://developer.chrome.com/extensions/webRequest) but this is not available for my "event page" extension.

Thank you for reporting this and enjoy the extension. ;)

**Comment by vaff** [comment]
A simple check would be if the title tag doesn't exist. it isn't a valid HTML document. And you shouldn't replace the title.

**Comment by sylouuu** [comment]
Do you have an URL example where this is not HTML?

**Comment by vaff** [comment]
Well it could still be formatted as html, but if the title tag doesn't exist, it isn't considered valid

**Comment by sylouuu** [comment]
Fixed in 0.18.2.
