### ISSUE TITLE
Restoring settings

### ISSUE THREAD

**Issue by tikolakin** [sylouuu/chrome-tab-modifier#67]
Hello, 
Thanks guys for such a lovely extension, I really appreciate the work you have done

Can you please tell me, whether settings of tabs are restored, when I sign in chrome on another computer?

Cheers

**Comment by sylouuu** [comment]
Hi @tikolakin,

Thanks for your feedback!

Do you mean " tab rules" by "settings of tabs"?

Your rules are saved locally, it means even if you sign-in from another computer you will get a fresh install of Tab Modifier. That's why you are able to export/import rules from the Settings view.

Ref. https://github.com/sylouuu/chrome-tab-modifier/issues/27

Best

**Comment by tikolakin** [comment]
Perfect, I didn't know about this feature (tbh, I didn't explore all the features)
It works like a charm, thanks.
Cheers
