### ISSUE TITLE
 Title {#abc} ignore if unfound

### ISSUE THREAD

**Issue by Paskovz** [sylouuu/chrome-tab-modifier#74]
Hello,

Can objects unfound in DOM be ignored in title ?

![image](https://cloud.githubusercontent.com/assets/2414825/24605229/46791c10-1868-11e7-8ffb-bc4e6a67dd36.png)

Great work btw I appreciate this extension a lot!

**Comment by sylouuu** [comment]
Hi @Paskovz;

Thanks for your feedback. I asked myself this question when doing this feature. And I concluded that I had to let any string intact.

- What about a user who wants to type `{#abc}` in a title but without interpretation?
- Consider `Hello {#abc} !`, if `{#abc}` is not found, you'll get `Hello  !` (2 spaces), this more weird that letting the selector

What do you think about that?

Best

**Comment by Paskovz** [comment]
Yeah I understand the struggle, I will try to use regex on url instead of using the dom.

So my url looks like that: _http://localhost/Details.aspx?class=abc&id=123&ref=qwerty
The title wanted is "abc 123"

Following your exemple, I tryed to keep things simple and made this regexp:
=(.*?)([^&]+)

Resulting
![image](https://cloud.githubusercontent.com/assets/2414825/24610748/1384871e-1880-11e7-88f2-7cd5acbf267e.png)

Still can't manage to retrieve the id (bar) that should be on $2

Is the regex wrong ?

Thank you!

**Comment by sylouuu** [comment]
I'm not a regexp expert. Try with this working example: https://github.com/sylouuu/chrome-tab-modifier/blob/master/tests/fixtures/tab_modifier.json#L84

**Comment by dbroytman** [comment]
@sylouuu, thanks for reviewing my pull request. I'll bring the conversation here to continue the topic. I'm glad you pointed me here, because I had similar thoughts.

After consideration, I agree that users may expect `{#abc}` not to be interpreted in the title. Altering the experience would be bad user experience.

I suggest to add a second selector type. `[#abc]` would be considered a optional selector.

`Hello {#abc} !` returns `Hello {#abc} !`
`Hello [#abc] !` returns `Hello  !`

This is similarly used in [YUIDoc](http://yui.github.io/yuidoc/syntax/index.html). Square brackets specify an optional parameter.

**Comment by sylouuu** [comment]
Interesting!

* How do you know which space to remove? Before or after `[#abc]`?
* You should also handle edge-cases like `Hello[#abc]!`

Best
