### ISSUE TITLE
does not work with pages without title tag

### ISSUE THREAD

**Issue by ataiger** [sylouuu/chrome-tab-modifier#79]
### Tab Modifier version

0.19.2

### Expected behavior

work with pages without <title> tag

(on these pages, chrome displays the url. what I want to do is to change that.)

### Actual behavior

does not work

### Steps to reproduce the behavior

thanks for nice work!

**Comment by sylouuu** [comment]
Hi @ataiger,

TM is HTML-based. There is no way to change a tab title without HTML (as I know). I'll add this known issue in the README.

Best

**Comment by ataiger** [comment]
thanks for quick response.

so the extension can change the content of the title tag, but cannot create a title tag if the page didn't have one in the first place?

**Comment by sylouuu** [comment]
I wondered if you talked about an HTML page without `<title>` tag or a non-HTML page?

Can you give me a link please?

**Comment by ataiger** [comment]
it is an html page without title tag

law.go.kr/법령/민법

I wonder if it matters but the url contains Korean letters


2017. 4. 19. 오후 6:25 Syl <notifications@github.com> 작성:

**Comment by sylouuu** [comment]
I found [why](https://github.com/sylouuu/chrome-tab-modifier/blob/release/0.19.2/src/js/content.js#L173) the title is not applied. At load, the title is an empty string because the website is loading dynamically. If I remove the empty string check it works.

I'll release a patch in few hours, be sure to opt-in the notification in TM settings to know when TM is updated.

Best

**Comment by ataiger** [comment]
thanks a lot!! ;)



2017. 4. 19. 오후 6:58 Syl <notifications@github.com> 작성:
