### ISSUE TITLE
Doesn't work with tabs using IE Tab extension

### ISSUE THREAD

**Issue by nickelnine** [sylouuu/chrome-tab-modifier#82]
_In case of bug report, please fill this template and remove italic lines_
_However, clear all :)_

### Tab Modifier version

`0.19.3`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

Modified tabs under IE Tab to display according to rule

### Actual behavior

IE Tab tabs appear as they are i.e. no modification

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the behavior_

1. Install IE Tab
2. Set a modification rule. I did cnn.com rename to news.
3. Open the rule tab with IE Tab

**Comment by sylouuu** [comment]
Hi @nickelnine,

Tab Modifier is available for Chrome and Opera.

IE Tab emulates IE and IE doesn't support browser extensions. That's why TM can't works.

In general, Chrome extensions can't access to other Chrome extensions. If an extension embeds a web page, TM can't be injected inside.

So there are 2 reasons for the actual behavior.

Bests
