### ISSUE TITLE
Feature Request - Only pin first match

### ISSUE THREAD

**Issue by jacobmack** [sylouuu/chrome-tab-modifier#92]
I like to keep a set of sites pinned, but Chrome doesn't give you an option to start the browser with your set homepages as pinned.  

Your plugin fixes this and that's awesome, but I'd like to make it so that only the first instance matching a rule is pinned, after that, leave it as tab.

For example, I keep our company's github page pinned, but often will follow links in chat to different PRs.  I don't want them all pinned, and I don't want to necessarily keep it unique, as I'll have multiple tabs open to github.  Pinning just the first one and then ignoring the rest would be great!

**Comment by sylouuu** [comment]
Hi @jacobmack 

Thanks for your suggestion. Instead of thinking about a first instance option, I thought about an "Exact match" detection.

It would fit your need. Example:

* Detection: `Exact`
* URL fragment: `https://github.com/sylouuu/chrome-tab-modifier`

Will not match `https://github.com/sylouuu/chrome-tab-modifier/issues/92`. What do you think about it?

Best

**Comment by jacobmack** [comment]
That could work, as long as the tab modifier won't de-pin a tab if it goes away from that exact match, as I do often roam around the various pages within each pin. 

Basically it would match on startup of Chrome when the pages were exact and then not fire unless I go to those exact pages later in different tabs.

**Comment by sylouuu** [comment]
I agree. I still think it could be an easy-to-implement workaround and this new detection type may benefit to many users.

**Comment by sylouuu** [comment]
0.20.0 incoming with "Exact" detection type.

Best
