### ISSUE TITLE
Protection isn't kicking in

### ISSUE THREAD

**Issue by nevir** [sylouuu/chrome-tab-modifier#95]
### Tab Modifier version

**Browser:** Chrome (62.0.3192.0)

**Extension version:** 0.20.0

### Expected behavior

Pressing cmd-w (or file -> close tab) on a protected tab should warn about it

### Actual behavior

When pressing cmd-w to close the current tab, tab protection doesn't kick in (the tab closes immediately without a prompt)

**Comment by sylouuu** [comment]
Hey @nevir,

Thanks for your feedback. I've done some researches about this. Since Chrome 60, the event `beforeunload` that triggers the protected action has been reworked. Check out the [official Google article](https://developers.google.com/web/updates/2017/06/chrome-60-deprecations#require_user_gesture_for_beforeunload_dialogs) and [this SO answer](https://stackoverflow.com/questions/45671818/javascript-not-working-after-chrome-update). In my opinion, this is a good decision made by Chrome for end users.

That means, the protected action on a TM rule may or may not works depending on your interaction with the page.

I'll add a short note to the README to reference this issue.

Best

**Comment by nevir** [comment]
Ah! Thanks for the details

**Comment by pflegende** [comment]
it is yet also (opera Version:66.0.3515.115)  
(especialy with the close-icon on every tab)

workaround:
immediately after open the tab:
on the right klick -> "close ..." then apears the message, - nice! -
and in follow up the close-icon also seems sensitiv ...

**Comment by ask-compu** [comment]
why is this issue closed if this problem still happens?
