### ISSUE TITLE
Using the extension offline

### ISSUE THREAD

**Issue by ataiger** [sylouuu/chrome-tab-modifier#97]
Hi, I am using chrome tab modifier on intranet.

When I try to open tab rules page on intranet, it does not load.

I can still use it by adding the rules by right click. Cannot edit rules though.

Can you make the extension usable on intranet? Thanks.

**Comment by 42degrees** [comment]
Reading between the lines I assume you mean you are on an Intranet that has no connection to the Internet?  If so, then the reason parts of this extension don't work is because some HTML pages in the extension don't ship with angular library files, they expect to be able to download angular JavaScript and CSS files from the Internet.

You could fix this in your isolated Intranet by creating a false server for ajax.googleapis.com.  If your local machine has a web server you can easily fake this by editing your hosts file and putting the above files in your local web root in the proper directory structure.  The only complexity is that the server has to serve them securely (https) since that's how they are being requested.

These are the files it currently requires (and where you can download them):

https://ajax.googleapis.com/ajax/libs/angular_material/1.1.1/angular-material.min.css
https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js
https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-route.min.js
https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-animate.min.js
https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-aria.min.js
https://ajax.googleapis.com/ajax/libs/angular_material/1.1.1/angular-material.min.js

Another choice that doesn't require secure hosting would be to copy the Tab Modifier extension out of the Chrome extension directory (look for "hcbgadmbdkiilgpifjgcakjehmafcjai", the location depends on your OS) into a user directory, delete the "_metadata" directory in the copy, enable extension debugging in Chrome, and using "Load unpacked extension" to load the copy into Chrome (Google "Load unpacked extension" for detailed instructions).  Then you could modify the HTML files to point to the above angular files in a local directory.  Make sure you export your Tab Modifier rules before doing this, so you can import them again, as the unpacked extension will get a different GUID and will not be able to see the "real" extension's data.

I'm sure that Syl was just trying to make the extension as small as possible and for the 99% it's a perfectly reasonable thing to do.

**Comment by sylouuu** [comment]
Thanks @42degrees for pointing on this workaround. In addition, TM works offline, but the Options page does not.

**Comment by ataiger** [comment]
Thank you for the answer!

**Comment by EC-O-DE** [comment]
Get ext called Decentraleyes, it downloads many CDN sources like angular.js and makes sites u go to use them from local - not such as Google servers.
